<?php

namespace Database\Seeders\webz;

use App\Models\Vendor;
use Illuminate\Database\Seeder;

class VendorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $vendors = [
            [
                'name' => 'Tech Solutions Inc.',
                'email' => 'contact@techsolutions.com',
                'phone' => '+1-555-2001',
                'address' => '123 Technology Way',
                'city' => 'Innovation City',
                'state' => 'CA',
                'zip_code' => '94043',
                'country' => 'USA',
                'tax_id' => 'TS123456789',
                'description' => 'Specializes in custom software development',
                'rating' => 4.7,
                'website' => 'https://www.techsolutions.com',
                'status' => 'active',
                'payment_terms' => 'NET30',
                'credit_limit' => 50000.00,
            ],
            [
                'name' => 'Global Suppliers Ltd',
                'email' => 'orders@globalsuppliers.com',
                'phone' => '+1-555-2002',
                'address' => '456 Supply Chain Blvd',
                'city' => 'Logistics City',
                'state' => 'TX',
                'zip_code' => '75001',
                'country' => 'USA',
                'tax_id' => 'GS456789012',
                'description' => 'Provides raw materials and supplies',
                'rating' => 4.9,
                'website' => 'https://www.globalsuppliers.com',
                'status' => 'active',
                'payment_terms' => 'NET60',
                'credit_limit' => 75000.00,
            ],
            [
                'name' => 'Cloud Infrastructure Co',
                'email' => 'services@cloudinfra.com',
                'phone' => '+1-555-2003',
                'address' => '789 Cloud Computing St',
                'city' => 'Tech Valley',
                'state' => 'VA',
                'zip_code' => '20101',
                'country' => 'USA',
                'tax_id' => 'CI789012345',
                'description' => 'Cloud hosting and infrastructure services',
                'rating' => 4.8,
                'website' => 'https://www.cloudinfra.com',
                'status' => 'active',
                'payment_terms' => 'NET30',
                'credit_limit' => 100000.00,
            ],
            [
                'name' => 'Marketing Experts Group',
                'email' => 'inquiries@marketingexperts.com',
                'phone' => '+1-555-2004',
                'address' => '321 Marketing Ave',
                'city' => 'Brand City',
                'state' => 'NY',
                'zip_code' => '10001',
                'country' => 'USA',
                'tax_id' => 'ME012345678',
                'description' => 'Digital marketing and advertising services',
                'rating' => 4.5,
                'website' => 'https://www.marketingexperts.com',
                'status' => 'active',
                'payment_terms' => 'NET45',
                'credit_limit' => 30000.00,
            ],
            [
                'name' => 'Office Essentials Inc',
                'email' => 'orders@officeessentials.com',
                'phone' => '+1-555-2005',
                'address' => '654 Office Supplies Dr',
                'city' => 'Business Center',
                'state' => 'IL',
                'zip_code' => '60601',
                'country' => 'USA',
                'tax_id' => 'OE345678901',
                'description' => 'Office supplies and furniture supplier',
                'rating' => 4.6,
                'website' => 'https://www.officeessentials.com',
                'status' => 'active',
                'payment_terms' => 'NET30',
                'credit_limit' => 15000.00,
            ],
            [
                'name' => 'Professional Services Network',
                'email' => 'contracts@profservices.net',
                'phone' => '+1-555-2006',
                'address' => '987 Professional Plaza',
                'city' => 'Consultant Town',
                'state' => 'MA',
                'zip_code' => '02101',
                'country' => 'USA',
                'tax_id' => 'PS678901234',
                'description' => 'Professional consulting and advisory services',
                'rating' => 4.4,
                'website' => 'https://www.profservices.net',
                'status' => 'active',
                'payment_terms' => 'NET60',
                'credit_limit' => 40000.00,
            ],
            [
                'name' => 'Security Solutions Ltd',
                'email' => 'info@securitysolutions.com',
                'phone' => '+1-555-2007',
                'address' => '147 Security Lane',
                'city' => 'Safe City',
                'state' => 'FL',
                'zip_code' => '33101',
                'country' => 'USA',
                'tax_id' => 'SS901234567',
                'description' => 'Cybersecurity and physical security services',
                'rating' => 4.9,
                'website' => 'https://www.securitysolutions.com',
                'status' => 'active',
                'payment_terms' => 'NET30',
                'credit_limit' => 60000.00,
            ],
            [
                'name' => 'Training Excellence Corp',
                'email' => 'training@trainingexcellence.com',
                'phone' => '+1-555-2008',
                'address' => '258 Education Rd',
                'city' => 'Learning Center',
                'state' => 'WA',
                'zip_code' => '98001',
                'country' => 'USA',
                'tax_id' => 'TE234567890',
                'description' => 'Corporate training and development programs',
                'rating' => 4.3,
                'website' => 'https://www.trainingexcellence.com',
                'status' => 'active',
                'payment_terms' => 'NET45',
                'credit_limit' => 25000.00,
            ],
            [
                'name' => 'Design Innovators Inc',
                'email' => 'creative@designinnovators.com',
                'phone' => '+1-555-2009',
                'address' => '369 Creative Blvd',
                'city' => 'Artistic City',
                'state' => 'CA',
                'zip_code' => '90210',
                'country' => 'USA',
                'tax_id' => 'DI567890123',
                'description' => 'Graphic design and creative services',
                'rating' => 4.7,
                'website' => 'https://www.designinnovators.com',
                'status' => 'active',
                'payment_terms' => 'NET30',
                'credit_limit' => 20000.00,
            ],
            [
                'name' => 'Equipment Rental Services',
                'email' => 'rentals@equipmentrental.com',
                'phone' => '+1-555-2010',
                'address' => '741 Machinery Ave',
                'city' => 'Industrial Town',
                'state' => 'OH',
                'zip_code' => '44001',
                'country' => 'USA',
                'tax_id' => 'ER890123456',
                'description' => 'Heavy machinery and equipment rental',
                'rating' => 4.8,
                'website' => 'https://www.equipmentrental.com',
                'status' => 'active',
                'payment_terms' => 'Weekly',
                'credit_limit' => 80000.00,
            ],
        ];

        foreach ($vendors as $vendorData) {
            Vendor::factory()->create($vendorData);
        }
    }
}